server:
  name: go-elasticsearch-rest-api
  port: 8080

elastic_search:
  url: "http://localhost:9200"

log:
  level: info
  map:
    time: "@timestamp"
    msg: message
    stacktrace: stacktrace
    caller: caller
    function: func

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size
  status: status

response:
  id: X-Response-Id
  correlation: X-Correlation-Id